name: Run Axis Bot

on:
  workflow_dispatch:  # run manually
  push:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Axis bot
        run: python bot/main.py
